### ISSUE TITLE
Environment variables for --basedir and --suite

### ISSUE THREAD

**Issue by jhthorsen** [ido50/Svsh#1]
I was just dropping by your project and notice that you don't provide any defaults for --basedir and --suite.  I have some suggestions:
- Check which tools are installed (By looking in $PATH?) and default from a prioritized list that you define.
- Allow the defaults to be set from %ENV. Like `SVSH_SUITE=perp` and `SVSH_BASEDIR=/etc/whatever`
- Defaulting --basedir to a value based on --suite. Something like `$HOME/whatever` or `/etc/something`. "whatever" or "something" could be the --suite value or "svsh". You can even look for both, and stop when you find the first directory.

Reasoning for my suggestion is that it's very boring to specify the same switches to a program, that rarely change. (?)

**Comment by ido50** [comment]
Hi. Thanks for the suggestions. I definitely get what you're saying. On my end I usually define a bash alias that opens up svsh for me with my "default" options, but I can see how this could be beneficial. I'll think about your suggestions and let you know what I've decided to implement (or return to you with further questions).

**Comment by jhthorsen** [comment]
No problem. :+1: 

I'm still not sure if this is the tool for me, but I wanted to drop in with some feedback anyway.

**Comment by ariscn** [comment]
+1!

**Comment by ido50** [comment]
This has been implemented in v1.2.0. If --suite is not provided, the SVSH_SUITE environment variable will be checked. If --basedir is not provided, the SVSH_BASE environment variable is checked, and then the default base directory used by the specific suite (for example, daemontools uses /service by default).
